-- AlterTable
ALTER TABLE "Project" ADD COLUMN "cropX" REAL NOT NULL DEFAULT 0.5;
ALTER TABLE "Project" ADD COLUMN "cropY" REAL NOT NULL DEFAULT 0.5;
ALTER TABLE "Project" ADD COLUMN "cropWidth" REAL NOT NULL DEFAULT 1;
ALTER TABLE "Project" ADD COLUMN "cropHeight" REAL NOT NULL DEFAULT 1;
